# Minicurso Introdução à ciência de dados e aprendizado de máquina usando Python
## Parte 3 - Bibliotecas Python para Representação e Manipulação de Dados

### 3.1. Numpy

In [1]:
import numpy as np

In [2]:
lista1 = [1, 2, 3]
array1 = np.array(lista1)
print(lista1)
print(array1)
print(array1.shape)
print(type(lista1))
print(type(array1))

[1, 2, 3]
[1 2 3]
(3,)
<type 'list'>
<type 'numpy.ndarray'>


In [3]:
lista2 = [
    [1, 2, 3], 
    [3, 4, 5]]
array2 = np.array(lista2)
print(array2)
print('linha 1: {}'.format(array2[0]))
print('média: {}'.format(np.average(array2)))

[[1 2 3]
 [3 4 5]]
linha 1: [1 2 3]
média: 3.0


In [4]:
array1 + array2

array([[2, 4, 6],
       [4, 6, 8]])

In [5]:
array1 * array2

array([[ 1,  4,  9],
       [ 3,  8, 15]])

In [6]:
a = np.zeros((3, 5))
print(a)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [7]:
type(a[0,0])

numpy.float64

In [8]:
b = np.zeros((5,), dtype=np.int)
print(b)

[0 0 0 0 0]


In [9]:
type(b[0])

numpy.int64

In [10]:
np.full(5, 2, dtype=np.float)

array([ 2.,  2.,  2.,  2.,  2.])

In [11]:
np.empty([3, 4])

array([[  0.00000000e+000,   0.00000000e+000,   2.20032080e-314,
          2.20052956e-314],
       [  2.15718181e-314,   2.15841748e-314,   0.00000000e+000,
          0.00000000e+000],
       [  2.15527200e-314,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000]])

In [12]:
c = np.random.rand(2, 3)
c

array([[ 0.04675169,  0.35659374,  0.52270546],
       [ 0.1219228 ,  0.26130959,  0.69137029]])

In [13]:
np.transpose(c)

array([[ 0.04675169,  0.1219228 ],
       [ 0.35659374,  0.26130959],
       [ 0.52270546,  0.69137029]])

In [45]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [46]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
d[:, 0]

array([1, 4, 7])

In [16]:
d[:, 1]

array([2, 5, 8])

In [17]:
d[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [18]:
d[:, 2]

array([3, 6, 9])

In [22]:
X = d[:,0:2]
y = d[:,2]
print(X)
print('')
print(y)

[[1 2]
 [4 5]
 [7 8]]

[3 6 9]


#### Notação: start:stop:step

In [24]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

#### Salvar e Ler em arquivo

In [27]:
np.save('/tmp/x.npy', x)
del(x)
x = np.load('/tmp/x.npy')
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
# Usar memory mapping quando o conteúdo não couber em memória RAM
x_mm = np.memmap('/tmp/x_mm.npy', dtype='float32', mode='w+', shape=(1000, 100))
x_mm[999][99] = 12.5
print(x_mm[999][99])

# Delete the memmap instance to close the file (the mmap file is not deleted). 
# Deletion flushes memory changes to disk before removing the object.
del(x_mm)

# Load
x_mm = np.memmap('/tmp/x_mm.npy', dtype='float32', mode='r', shape=(1000, 100))
print(x_mm[999][99])

12.5
12.5
